services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - VITE_API_URL=${VITE_API_URL}
      - VITE_API_SECRET=${VITE_API_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm dev"
